"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./resturantComponents/nav";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { createContext, useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export const loginContext = createContext();

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [islogin, setIslogin] = useState(false);

  return (
    <html lang="en">
      <body className={inter.className}>
        <loginContext.Provider value={{ islogin, setIslogin }}>
          <Nav />
          {children}
          <ToastContainer />
        </loginContext.Provider>
      </body>
    </html>
  );
}
