import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./resturantComponents/nav";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Sessionwrapper from "../sessionprovider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sessionwrapper>
          <Nav />
          {children}
          <ToastContainer />
        </Sessionwrapper>
      </body>
    </html>
  );
}
